name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore DiagnosticsTools.sln

      - name: Build
        run: dotnet build DiagnosticsTools.sln -c Release --no-restore

      - name: Test
        run: dotnet test DiagnosticsTools.sln -c Release --no-build --verbosity normal

      - name: Pack
        run: dotnet pack DiagnosticsTools.sln -c Release --no-build -o artifacts/nuget /p:ContinuousIntegrationBuild=true

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics-tools-nuget
          path: artifacts/nuget/
